trigger:
  branches:
    include:
      - main
  paths:
    include:
    - iac/*

jobs:
- template: template-infrastructure-cd.yaml
  parameters:
 # INFRASTRUCTURE
    KEY: prod.tstate
    TF_VAR_environment: production
    TF_VAR_prefix: prodenv
